### ISSUE TITLE
NerConverter index out of range when it’s used after BertEmbeddings and ner_dl_bert

### ISSUE THREAD

**Issue by dukegris** [JohnSnowLabs/spark-nlp#603]
Using NerConverter in some situations produces an exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

## Description

In a pipeline wirh nerconverter and with some text, the pipeline throws an exception

## Expected Behavior

Obviously end the pipeline

## Current Behavior

```
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>)
  at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1066)
  at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:152)
  at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:50)
  at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:32)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at scala.collection.immutable.List.map(List.scala:296)

...

  ... 107 elided
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.substring(String.java:1931)
  at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$$anonfun$fromIOB$1.apply$mcVI$sp(NerTagsEncoding.scala:51)
```

## Steps to Reproduce

```
import com.johnsnowlabs.nlp.{SparkNLP, DocumentAssembler, Finisher, AnnotatorType}
import com.johnsnowlabs.nlp.{RecursivePipeline, LightPipeline}
import com.johnsnowlabs.nlp.pretrained.PretrainedPipeline
import com.johnsnowlabs.nlp.embeddings.{BertEmbeddings, WordEmbeddingsFormat, WordEmbeddingsModel}
import com.johnsnowlabs.nlp.annotators.{Tokenizer, Normalizer}
import com.johnsnowlabs.nlp.annotators.ner.NerConverter
import com.johnsnowlabs.nlp.annotators.ner.dl.{NerDLModel, PretrainedNerDL} 
import com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel
import com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector
import com.johnsnowlabs.util.Benchmark

import org.apache.spark.ml.{Pipeline, PipelineModel}

import spark.implicits._

import scala.util.matching.Regex

val emptyData = spark.emptyDataset[String].toDF("text")

val testData = spark.createDataFrame(Seq(
	(18, "Ehlers-Danlos syndrome, vascular type (vEDS) (MIM #130050) is an autosomal dominant disorder caused by type III procollagen gene (COL3A1) mutations. Most COL3A1 mutations are detected y using total RNA from patient-derived fibroblasts, which requires an invasive skin biopsy. High-resolution melting curve analysis (hrMCA) has recently been developed as a post-PCR mutation scanning method which enables simple, rapid, cost-effective, and highly sensitive mutation screening of large genes. We established a hrMCA method to screen for COL3A1 mutations using genomic DNA. PCR primers pairs for COL3A1 (52 amplicons) were designed to cover all coding regions of the 52 exons, including the splicing sites. We used 15 DNA samples (8 validation samples and 7 samples of clinically suspected vEDS patients) in this study. The eight known COL3A1 mutations in validation samples were all successfully detected by the hrMCA. In addition, we identified five novel COL3A1 mutations, including one deletion (c.2187delA) and one nonsense mutation (c.2992C>T) that could not be determined by the conventional total RNA method. Furthermore, we established a small amplicon genotyping (SAG) method for detecting three high frequency coding-region SNPs (rs1800255:G>A, rs1801184:T>C, and rs2271683:A>G) in COL3A1 to differentiate mutations before sequencing. The use of hrMCA in combination with SAG from genomic DNA enables rapid detection of COL3A1 mutations with high efficiency and specificity. A better understanding of the genotype-phenotype correlation in COL3A1 using this method will lead to improve in diagnosis and treatment."),
	(99, "HGNC:37133")
)).toDF("id", "text")

val document = new DocumentAssembler().
	setInputCol("text").
	setOutputCol("document").
	setCleanupMode("shrink")

val sentence = new SentenceDetector().
	setInputCols("document").
	setOutputCol("sentences")

val token = new Tokenizer().
	setInputCols("sentences").
	setOutputCol("token")

val pos = PerceptronModel.pretrained().
	setInputCols(Array("sentences", "token")).
	setOutputCol("pos")
 
val embeddings = BertEmbeddings.
	pretrained("bert_uncased", "en").
	setMaxSentenceLength(4096).
	setDimension(1024).
	setInputCols(Array("sentences")).
	setOutputCol("embeddings")

val ner = NerDLModel.
	pretrained("ner_dl_bert").
	setInputCols(Array("sentences", "token", "embeddings")).
	setOutputCol("ner")

val converter = new NerConverter().
	setInputCols(Array("sentences", "token", "ner")).
	setOutputCol("ner_chunk")

val finisher = new Finisher().
	setInputCols(Array(
		"document", "sentences", 
		"token", "pos", "embeddings", 
		"ner")).
	setIncludeMetadata(true).
	setCleanAnnotations(false)

val pipeline = new RecursivePipeline().
	setStages(Array(
		document,
		sentence,
		token,
		pos,
		embeddings,
		ner,
		converter,
		finisher
))

val model = pipeline.fit(emptyData)

val result = model.transform(testData)

result.show

```
If you exclude converter from the pipeline:
```
val pipeline = new RecursivePipeline().
	setStages(Array(
		document,
		sentence,
		token,
		pos,
		embeddings,
		ner,
		finisher
))

val model = pipeline.fit(emptyData)

val result = model.transform(testData)

result.show
```
results are correct
```
+---+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------------+---------------------------+-----------------------+---------------------+----------------------------+---------------------+
| id|                text|            document|           sentences|               token|                 pos|          embeddings|                 ner|   finished_document|  finished_sentences|      finished_token|        finished_pos| finished_embeddings|        finished_ner|finished_document_metadata|finished_sentences_metadata|finished_token_metadata|finished_pos_metadata|finished_embeddings_metadata|finished_ner_metadata|
+---+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------------+---------------------------+-----------------------+---------------------+----------------------------+---------------------+
| 18|Ehlers-Danlos syn...|[[document, 0, 16...|[[document, 0, 14...|[[token, 0, 12, E...|[[pos, 0, 12, NNP...|[[word_embeddings...|[[named_entity, 0...|[Ehlers-Danlos sy...|[Ehlers-Danlos sy...|[Ehlers-Danlos, s...|[NNP, NN, ,, NN, ...|[eh, ##lers, -, d...|[O, O, O, O, O, I...|           [[sentence, 0]]|       [[sentence, 0], [...|   [[sentence, 0], [...| [[word, Ehlers-Da...|        [[sentence, 0], [...| [[word, ehlers], ...|
| 99|          HGNC:37133|[[document, 0, 9,...|[[document, 0, 9,...|[[token, 0, 9, HG...|[[pos, 0, 9, NNP,...|[[word_embeddings...|[[named_entity, 0...|        [HGNC:37133]|        [HGNC:37133]|        [HGNC:37133]|               [NNP]|[h, ##gn, ##c, :,...|           [O, O, O]|           [[sentence, 0]]|            [[sentence, 0]]|        [[sentence, 0]]| [[word, HGNC:37133]]|        [[sentence, 0], [...| [[word, hgnc], [w...|
+---+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------+--------------------------+---------------------------+-----------------------+---------------------+----------------------------+---------------------+
```
## Your Environment

* Version used: 2.1.0 in Spark 2.4.3
* Browser Name and version: spark-shell
* Operating System and version (desktop or mobile): Windows and Linux
* Link to your project: https://github.com/dukegris/TFM

**Comment by maziyarpanahi** [comment]
Hi,

There were two bugs related to this specific pipeline which are fixed in 2.2.0:

1- we fixed something in NerConverter to avoid crash (not in your case)
2- we fixed BertEmbeddings for not having correct alignment with our own Tokenizer (exactly your case, tokens are not matches with BertEmbeddings tokenizer so it cannot match them)

If you change your embeddings to WordEmbeddings and NerDLModel to “ner_dl” then you see no error. This one is the Bert issue and it’s fixed in next release.

Could you please try our new pre-release 2.2.0-rc3? Fixes are there but you need to train your own Bert Model and load it. We haven’t published any pretrained for the pre-release version.

Let me know if you have any question for how to create Bert model for Spark NLP.

**Comment by dukegris** [comment]
It looks that the new 2.2.0 version works ok and syncronize correctly the annotations. Thx

**Comment by dukegris** [comment]
After migrate to version 2.2.0 and generat the bert embedding models with /python/tensorflow/bert/create_bert.ipynb, we still have the java.lang.StringIndexOutOfBoundsException: String index out of range: -1 with NerConverter. 
As you said, the tokens matches correctly whit the bert ner model, but when you include in the pipeline the converter, then you get the exception.

The code for 2.2.0 to replicate it, is the same as before except for the embedding (loading the new models instead of pretrained of course):
```
val embeddings = BertEmbeddings.
	pretrained("bert_uncased", "en").
	setMaxSentenceLength(4096).
	setDimension(1024).
	setInputCols(Array("sentences", "token")).
	setOutputCol("embeddings")
```

**Comment by maziyarpanahi** [comment]
Could you please update your code and put your entire pipeline?

**Comment by dukegris** [comment]
### The code:
```
import com.johnsnowlabs.nlp.{SparkNLP, DocumentAssembler, Finisher, AnnotatorType}
import com.johnsnowlabs.nlp.{RecursivePipeline, LightPipeline}
import com.johnsnowlabs.nlp.pretrained.PretrainedPipeline
import com.johnsnowlabs.nlp.embeddings.{BertEmbeddings, WordEmbeddingsFormat, WordEmbeddingsModel}
import com.johnsnowlabs.nlp.annotators.{Tokenizer, Normalizer}
import com.johnsnowlabs.nlp.annotators.ner.NerConverter
import com.johnsnowlabs.nlp.annotators.ner.dl.{NerDLModel, PretrainedNerDL} 
import com.johnsnowlabs.nlp.annotators.pos.perceptron.PerceptronModel
import com.johnsnowlabs.nlp.annotators.sbd.pragmatic.SentenceDetector
import com.johnsnowlabs.util.Benchmark

import org.apache.spark.ml.{Pipeline, PipelineModel}

import spark.implicits._

import scala.util.matching.Regex

val emptyData = spark.emptyDataset[String].toDF("text")

val testData = spark.createDataFrame(Seq(
	(18, "Ehlers-Danlos syndrome, vascular type (vEDS) (MIM #130050) is an autosomal dominant disorder caused by type III procollagen gene (COL3A1) mutations. Most COL3A1 mutations are detected y using total RNA from patient-derived fibroblasts, which requires an invasive skin biopsy. High-resolution melting curve analysis (hrMCA) has recently been developed as a post-PCR mutation scanning method which enables simple, rapid, cost-effective, and highly sensitive mutation screening of large genes. We established a hrMCA method to screen for COL3A1 mutations using genomic DNA. PCR primers pairs for COL3A1 (52 amplicons) were designed to cover all coding regions of the 52 exons, including the splicing sites. We used 15 DNA samples (8 validation samples and 7 samples of clinically suspected vEDS patients) in this study. The eight known COL3A1 mutations in validation samples were all successfully detected by the hrMCA. In addition, we identified five novel COL3A1 mutations, including one deletion (c.2187delA) and one nonsense mutation (c.2992C>T) that could not be determined by the conventional total RNA method. Furthermore, we established a small amplicon genotyping (SAG) method for detecting three high frequency coding-region SNPs (rs1800255:G>A, rs1801184:T>C, and rs2271683:A>G) in COL3A1 to differentiate mutations before sequencing. The use of hrMCA in combination with SAG from genomic DNA enables rapid detection of COL3A1 mutations with high efficiency and specificity. A better understanding of the genotype-phenotype correlation in COL3A1 using this method will lead to improve in diagnosis and treatment."),
	(99, "HGNC:37133")
)).toDF("id", "text")

val document = new DocumentAssembler().
	setInputCol("text").
	setOutputCol("document").
	setCleanupMode("shrink")

val sentence = new SentenceDetector().
	setInputCols("document").
	setOutputCol("sentences")

val token = new Tokenizer().
	setInputCols("sentences").
	setOutputCol("token")

val pos = PerceptronModel.pretrained().
	setInputCols(Array("sentences", "token")).
	setOutputCol("pos")

val embeddings = BertEmbeddings.
	load("models/uncased_L-12_H-768_A-12_M-128_B-32").
	setMaxSentenceLength(512).
	setDimension(768).
	setInputCols(Array("sentences", "token")).
	setOutputCol("embeddings")

val ner = NerDLModel.
	pretrained("ner_dl_bert").
	setInputCols(Array("sentences", "token", "embeddings")).
	setOutputCol("ner")

val converter = new NerConverter().
	setInputCols(Array("sentences", "token", "ner")).
	setOutputCol("ner_chunk")

val finisher = new Finisher().
	setInputCols(Array(
		"document", "sentences", 
		"token", "pos", "embeddings", 
		"ner")).
	setIncludeMetadata(true).
	setCleanAnnotations(false)

val pipeline = new RecursivePipeline().
	setStages(Array(
		document,
		sentence,
		token,
		pos,
		embeddings,
		ner,
		converter,
		finisher
))

val model = pipeline.fit(emptyData)

val result = model.transform(testData)

result.show

```
### Execution .1 
```
 val embeddings = BertEmbeddings.
     |   load("models/uncased_L-12_H-768_A-12_M-128_B-32").
     |   setMaxSentenceLength(512).
     |   setDimension(768).
     |   setInputCols(Array("sentences", "token")).
     |   setOutputCol("embeddings")

result.show
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>)
  at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1066)
  at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:152)
...
  at org.apache.spark.sql.Dataset.show(Dataset.scala:704)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:713)
  ... 51 elided
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.substring(String.java:1931)
  at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$$anonfun$fromIOB$1.apply$mcVI$sp(NerTagsEncoding.scala:52)
  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
  at com.johnsnowlabs.nlp.annotators.ner.NerTagsEncoding$.fromIOB(NerTagsEncoding.scala:45)
  at com.johnsnowlabs.nlp.annotators.ner.NerConverter$$anonfun$2.apply(NerConverter.scala:30)
  at com.johnsnowlabs.nlp.annotators.ner.NerConverter$$anonfun$2.apply(NerConverter.scala:30)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)

```

### Execution .2, using the BERT models from 2019_05_30

```
 val embeddings = BertEmbeddings.
     |   load("models/wwm_uncased_L-24_H-1024_A-16_M-128_B-32").
     |   setMaxSentenceLength(512).
     |   setDimension(1024).
     |   setInputCols(Array("sentences", "token")).
     |   setOutputCol("embeddings")
	 
	 
	 
org.apache.spark.SparkException: Failed to execute user defined function($anonfun$dfAnnotate$1: (array<array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>>) => array<struct<annotatorType:string,begin:int,end:int,result:string,metadata:map<string,string>,embeddings:array<float>,sentence_embeddings:array<float>>>)
  at org.apache.spark.sql.catalyst.expressions.ScalaUDF.eval(ScalaUDF.scala:1066)
  at org.apache.spark.sql.catalyst.expressions.Alias.eval(namedExpressions.scala:152)
  at org.apache.spark.sql.catalyst.expressions.InterpretedProjection.apply(Projection.scala:50)

...

  at org.apache.spark.sql.Dataset.show(Dataset.scala:713)
  ... 51 elided
Caused by: java.lang.IllegalArgumentException: Input to reshape is a tensor with 31192 values, but the requested shape requires a multiple of 858
         [[{{node Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](word_repr_1/concat, Reshape/shape)]]
  at org.tensorflow.Session.run(Native Method)
  at org.tensorflow.Session.access$100(Session.java:48)
  at org.tensorflow.Session$Runner.runHelper(Session.java:314)
  at org.tensorflow.Session$Runner.run(Session.java:264)
  at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2.apply(TensorflowNer.scala:78)
  at com.johnsnowlabs.ml.tensorflow.TensorflowNer$$anonfun$predict$2.apply(TensorflowNer.scala:56)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)

```
We are using Linux Ubuntu,
Intel(R) Xeon(R) W-2155 CPU @ 3.30GHz (10 cores)
NVIDIA Corporation GV100GL [Quadro GV100]

### NOTE: 
I'm not sure how to produce a NER DL Model using BERT from CONLL2003 files. We are using spark-nlp/python/tensorflow/ner/conll2003_ner.ipynb but the save process fails (Line 62: save_models(export_dir) in spark-nlp/python/tensorflow/ner/ner_model_saver.py. We change the code to save the model but it's not compatble with the one neede by NerDLModel.
The other approach is to use NerDLApproach. This one was out first approach, but it needs NerConverter and that's the origin of the bug

**Comment by maziyarpanahi** [comment]
The problem is ner_dl_bert, we have to re-train it with the fixed BERT models.

That notebook is not the way you train NER in Spark NLP. I’ll be removing it soon as it was for debugging purposes. Could you please join Slack and ask how to train NER with NerDLApproach?

**Comment by maziyarpanahi** [comment]
NerConverter doesn’t have any bug, it’s tested. You are using an old pretrained ner model. If you train your own NerDLApproach with 2.2.0 it won’t be any issue. It’s been heavily tested. 
And under no circumstances change anything in python/tensorflow as those are required to create graph and bert. Just forget about our pretrained ner model for bert and ignore that notebook entirely. You don’t need any of those. The graph for conll 2003 comes with the library, so just train it by NerDLApproach please :)

**Comment by dukegris** [comment]
Fixed. 
Apparently, we should train the NER models with the same parameters as those related to the BERT model and should not be mixed to avoid the behaviors described above, so, we obtain the BERT model trained with create_bert.ipynb and then train with NerDLApproach obtaining a Ner model for each Bert Model.

**Comment by maziyarpanahi** [comment]
Exactly! By the end of this week I am going to upload all the new BERT related models/pipelines to avoid users training them by themselves.
